### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by unixorn** [ston1x/sunrise-ruby#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a license - if you don't have one in mind,  I recommend [choosealicense.com](https://choosealicense.com) to help choose one.

**Comment by ston1x** [comment]
@unixorn thank you for this suggestion, I am using the GPL-3.0 license now. Feel free to add it to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins)!
